Brand new examples for chapter 5
AWSinAction/code3 pull request #11
Opened 2022-05-25 09:22 UTC by andreaswittig

Three brand new examples for chapter 5:

Deploying Etherpad on EC2 with ...

... CloudFormation, ASG, and User Data
... CodeDeploy
... Packer

2022-05-25 10:42 UTC, michaelwittig requested changes

2022-05-25 10:42 UTC, michaelwittig commented on chapter05/cloudformation.yaml
> +      HealthCheckType: EC2 # TODO Change to ELB
TODO :)

2022-05-25 10:42 UTC, michaelwittig commented on chapter05/codedeploy.yaml
> +      HealthCheckType: EC2 # TODO Change to ELB
TODO

2022-05-25 10:42 UTC, michaelwittig commented on chapter05/etherpad.pkr.hcl
> +      "git clone --depth 1 --branch 1.8.18 https://github.com/ether/etherpad-lite.git",
please clone repo to AWSinAction org

2022-05-25 10:42 UTC, michaelwittig commented on chapter05/cloudformation.yaml
> +            git clone --depth 1 --branch ${EtherpadVersion} https://github.com/ether/etherpad-lite.git
please clone repo to AWSinAction org

2022-05-25 10:42 UTC, michaelwittig commented on chapter05/packer.yaml
> +      HealthCheckType: EC2 # TODO Change to ELB
TODO

2022-05-31 08:22 UTC, andreaswittig commented on chapter05/cloudformation.yaml
> +            git clone --depth 1 --branch ${EtherpadVersion} https://github.com/ether/etherpad-lite.git
Good point, thanks!

2022-05-31 08:24 UTC, merged