Updating examples for chapter 10
AWSinAction/code3 pull request #15
Opened 2022-08-23 08:44 UTC by andreaswittig

Please run `yamllint folder/template.yaml` and `aws cloudformation validate-template --template-body file://folder/template.yaml` before

2022-08-23 09:26 UTC, michaelwittig requested changes

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs-provisioned.yaml
> +      SecurityGroupEgress:
wir haben sonst eigentlich nirgends egress regelen? weglassen?

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs-provisioned.yaml
>            bash -ex << "TRY"
kannst du das noch mit `trap` machen?

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs-provisioned.yaml
>            bash -ex << "TRY"
`trap`

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs-backup.yaml
> +          bash -ex << "TRY"
`trap`

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs-backup.yaml
> +          bash -ex << "TRY"
`trap`

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs.yaml
> +      SecurityGroupEgress:
egress?

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs-backup.yaml
> +      - IpProtocol: tcp
bisher haben ir keine egress regeln definiert? weglassen?

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs.yaml
>            bash -ex << "TRY"
`trap`

2022-08-23 09:26 UTC, michaelwittig commented on chapter10/efs.yaml
>            bash -ex << "TRY"
`trap`

2022-08-24 09:16 UTC, andreaswittig commented on chapter10/efs-provisioned.yaml
> +      SecurityGroupEgress:
✅

2022-08-24 18:59 UTC, andreaswittig commented on chapter10/efs-provisioned.yaml
>            bash -ex << "TRY"
✅

2022-08-24 18:59 UTC, andreaswittig commented on chapter10/efs-provisioned.yaml
>            bash -ex << "TRY"
✅

2022-08-24 18:59 UTC, andreaswittig commented on chapter10/efs-backup.yaml
> +          bash -ex << "TRY"
✅

2022-08-24 18:59 UTC, andreaswittig commented on chapter10/efs.yaml
> +      SecurityGroupEgress:
✅

2022-08-24 18:59 UTC, andreaswittig commented on chapter10/efs-backup.yaml
> +      - IpProtocol: tcp
✅

2022-08-24 18:59 UTC, andreaswittig commented on chapter10/efs.yaml
>            bash -ex << "TRY"
✅

2022-08-24 18:59 UTC, andreaswittig commented on chapter10/efs.yaml
>            bash -ex << "TRY"
✅

2022-08-24 19:00 UTC, andreaswittig commented on chapter10/efs-backup.yaml
> +          bash -ex << "TRY"
✅

2022-08-24 19:00 UTC, merged