Updating chapter 15
AWSinAction/code3 pull request #3
Opened 2022-01-17 09:38 UTC by andreaswittig

2022-01-18 18:30 UTC, michaelwittig commented on chapter15/url2png/config.json
> +  "QueueUrl": "https://sqs.us-east-1.amazonaws.com/486555357186/url2png",
is this file changed by accident?

2022-01-18 18:49 UTC, michaelwittig requested changes

2022-01-18 18:55 UTC, michaelwittig commented on chapter15/url2png/index.js
> +    console.log('PNG will be soon available at http://' + config.Bucket + '.s3.amazonaws.com/' + id + '.png');
ok. scheint auch so zu funktionieren

2022-01-20 12:03 UTC, andreaswittig commented on chapter15/url2png/config.json
> +  "QueueUrl": "https://sqs.us-east-1.amazonaws.com/486555357186/url2png",
Ups. 🙈

2022-01-20 12:05 UTC, andreaswittig commented on chapter15/url2png/index.js
> +    console.log('PNG will be soon available at http://' + config.Bucket + '.s3.amazonaws.com/' + id + '.png');
Might work for `us-east-1` only. Will fix.

2022-01-20 12:08 UTC, andreaswittig commented on chapter15/url2png/index.js
> +    console.log('PNG will be soon available at http://' + config.Bucket + '.s3.amazonaws.com/' + id + '.png');
Tested for `eu-west-1`. Works fine.

2022-01-20 12:11 UTC, merged